Version 2.8

diff --git a/.github/workflows/blue-green-deploy.yml b/.github/workflows/blue-green-deploy.yml
--- a/.github/workflows/blue-green-deploy.yml
+++ b/.github/workflows/blue-green-deploy.yml
@@ -31,21 +31,15 @@ jobs:
     
           - name: Test on blue version
             run: |
-                RESPONSE=$(curl -s https://kateserna.github.io/asignacion_servidores_web/)
-                echo "$RESPONSE"
-                if [[ "$RESPONSE" != *"Version: 2.5"* ]]; then
-                    echo "Test Success: Las pruebas pasaron exitosamente."
+                if grep "Version: 2.8" index.html; then
+                    echo "Test Success: Las pruebas a blue pasaron exitosamente."
+                    echo "La versión blue está lista para ser promovida."
                 else
-                    echo "Test Failed: Las pruebas fallaron, la verion blue no tiene el texto esperado."
-                    echo "Realizando rollback a la versión green."
+                    echo "Test Failed: Las pruebas  a blue fallaron, la versión blue no tiene el texto esperado."
                     exit 1
                 fi
     
-          - name: Notify Test Success
-            if: success()
-            run: echo "La versión blue está lista para ser promovida."
-    
-          - name: Promote Blue to Green
+          - name: Promote blue to Green
             if: success()
             run: |
                 git status
@@ -53,6 +47,20 @@ jobs:
                 git merge origin blue
                 git push
                 echo "La versión Blue ha sido promovida a Green."
+
+          - name: Test on green version
+            run: |
+                if grep "Version: 2.8" index.html; then
+                    echo "Test Success: Las pruebas a green pasaron exitosamente."
+                    echo "La versión green está lista para ser desplegada a GitHub Pages."
+                else
+                    echo "Test Failed: Las pruebas a green fallaron, la versión green no tiene el texto esperado."
+                    echo "Realizando rollback a la versión green."
+                    git reset --hard origin/green
+                    git push --force
+                    echo "Rollback realizado. Saliendo con error!"
+                    exit 1
+                fi
 
           - name: Upload files
             uses: actions/upload-pages-artifact@v3
