Version 2.6

diff --git a/.github/workflows/blue-green-deploy.yml b/.github/workflows/blue-green-deploy.yml
--- a/.github/workflows/blue-green-deploy.yml
+++ b/.github/workflows/blue-green-deploy.yml
@@ -31,15 +31,15 @@ jobs:
     
           - name: Test on blue version
             run: |
-              RESPONSE=$(curl -s https://kateserna.github.io/asignacion_servidores_web/)
-              echo "$RESPONSE" 
-              if [[ "$RESPONSE" != *"Version: 2.5"* ]]; then
-                echo "Test Success: Las pruebas pasaron exitosamente."
-              else
-                echo "Test Failed: Las pruebas fallaron, la verion blue no tiene el texto esperado."
-                echo "Realizando rollback a la versión green."
-                exit 1
-              fi
+                RESPONSE=$(curl -s https://kateserna.github.io/asignacion_servidores_web/)
+                echo "$RESPONSE"
+                if [[ "$RESPONSE" != *"Version: 2.5"* ]]; then
+                    echo "Test Success: Las pruebas pasaron exitosamente."
+                else
+                    echo "Test Failed: Las pruebas fallaron, la verion blue no tiene el texto esperado."
+                    echo "Realizando rollback a la versión green."
+                    exit 1
+                fi
     
           - name: Notify Test Success
             if: success()
